apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    tier: front-end
spec:
  type: NodePort
  selector:
    tier: front-end
    app: web
  ports:
    - port: 80
      nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    tier: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      tier: front-end
  template:
    metadata:
      labels:
        app: web
        tier: front-end
    spec:
      containers:
        - name: web
          image: skaffold-demo-front-end-web
          imagePullPolicy: Never
          ports:
            - containerPort: 80
