apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: skaffold-demo-front-end
build:
  artifacts:
    - image: skaffold-demo-front-end-web
deploy:
  kubectl:
    manifests:
      - kubernetes.yml
