apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    tier: back-end
spec:
  type: NodePort
  selector:
    tier: back-end
    app: api
  ports:
    - port: 80
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    tier: back-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
      tier: back-end
  template:
    metadata:
      labels:
        app: api
        tier: back-end
    spec:
      containers:
        - name: api
          image: skaffold-demo-back-end-api
          imagePullPolicy: Never
          ports:
            - containerPort: 80
